load("@rules_rust//rust:defs.bzl", "rust_library")

filegroup(
    name = "srcs",
    srcs = [
        "bitflags.rs",
        "compat.rs",
        "debug.rs",
        "dirent.rs",
        "timestamp.rs",
    ],
    visibility = ["//fuse:__subpackages__"],
)
