[package]
name = "fuse-std"
version = "0.0.1"
authors = ["John Millikin <john@john-millikin.com>"]
license = "Apache-2.0"
edition = "2021"

[lib]
name = "fuse_std"
path = "fuse-std.rs"

[dependencies]
fuse = { version = "0.0.1", path = "../fuse" }

