[package]
name = "fuse"
version = "0.0.1"
authors = ["John Millikin <john@john-millikin.com>"]
license = "Apache-2.0"
edition = "2018"

[lib]
name = "fuse"

[dependencies]
libc = { version = "0.2.*", optional = true }

[features]
default = ["std"]
std = []

libc_fuse_mount = ["libc"]

syscall_fuse_mount = []

unstable_bmap = []
unstable_ioctl = []
unstable_setattr = []
